/*
 * Structured report generator — ESPR-inspired sections. Deterministic string
 * interpolation (spec §4.11.4 "Deterministic Data Anchoring"), never LLM.
 */

import {
  Differential,
  GA,
  GROUP_ORDER,
  Parameter,
  PARAMETERS,
  ZResult,
  formatPct,
  formatZ,
  gaToDecimalWeeks,
} from "./biometry";

export type ReportContext = {
  ga: GA;
  fieldStrength: string; // "1.5T" | "3T" | "0.55T"
  motion: string; // "None" | "Mild" | "Moderate" | "Severe"
  referenceSet: string;
  values: Record<string, number | null>;
  zs: Record<string, ZResult | null>;
  dxs: Differential[];
};

const bandPhrase = (z: number) => {
  const a = Math.abs(z);
  if (a <= 1) return "within the normal range";
  if (a <= 2) return "mildly deviated from the expected mean";
  if (a <= 3) return "moderately deviated from the expected mean";
  return "markedly deviated from the expected mean";
};

const paramLine = (
  p: Parameter,
  x: number,
  zr: ZResult,
): string => {
  const flag = zr.extrapolated ? " [extrapolated outside validated GA range]" : "";
  return `${p.name}: ${x.toFixed(1)} mm (z ${formatZ(zr.z)}, ${formatPct(
    zr.percentile,
  )} percentile, model: ${zr.sourceLabel})${flag} — ${bandPhrase(zr.z)}.`;
};

export function generateReport(ctx: ReportContext): string {
  const { ga, fieldStrength, motion, referenceSet, values, zs, dxs } = ctx;
  const gaLabel = `${ga.weeks}w ${ga.days}d (${gaToDecimalWeeks(ga).toFixed(1)} weeks)`;

  const lines: string[] = [];
  lines.push("CLINICAL INDICATION");
  lines.push(
    `Fetal brain MRI at ${gaLabel} for evaluation of brain development.`,
  );
  lines.push("");

  lines.push("TECHNIQUE");
  lines.push(
    `Multiplanar T2-weighted single-shot fast spin-echo imaging of the fetal brain at ${fieldStrength}. Motion artefact: ${motion.toLowerCase()}. Reference set: ${referenceSet}.`,
  );
  lines.push("");

  lines.push("FINDINGS");
  for (const group of GROUP_ORDER) {
    const inGroup = PARAMETERS.filter((p) => p.group === group);
    const measured = inGroup.filter((p) => values[p.id] != null);
    if (measured.length === 0) continue;
    lines.push(`— ${group.toUpperCase()} —`);
    for (const p of measured) {
      const x = values[p.id]!;
      const zr = zs[p.id]!;
      lines.push(`  • ${paramLine(p, x, zr)}`);
    }
    lines.push("");
  }

  lines.push("IMPRESSION");
  const anyAbnormal = PARAMETERS.some((p) => {
    const z = zs[p.id];
    return z != null && Math.abs(z.z) > 2;
  });
  if (!anyAbnormal && Object.values(values).some((v) => v != null)) {
    lines.push(
      "All measured fetal brain biometric parameters are within the central 95% reference range for the stated gestational age. No quantitative evidence of biometric abnormality.",
    );
  } else if (anyAbnormal) {
    lines.push(
      "Biometric deviations were identified (see FINDINGS). The following differential considerations are suggested by the calculator's evidence-based trigger engine, ranked by likelihood:",
    );
    dxs.forEach((dx, i) => {
      lines.push(`  ${i + 1}. ${dx.title} — ${dx.severity.toUpperCase()} — ${dx.oneLine}`);
    });
    lines.push("");
    lines.push(
      "Correlation with detailed neurosonography, maternal history, genetic testing, and TORCH screening is recommended as clinically appropriate.",
    );
  } else {
    lines.push(
      "No measurements entered. Please enter biometric values to generate an impression.",
    );
  }

  lines.push("");
  lines.push(
    "— Generated by the Fetal Brain MRI Biometry Calculator (prototype). Deterministic string interpolation; no PHI stored.",
  );

  return lines.join("\n");
}
